#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""把 data/*.json 与 src/static/*.js 内联进 src/pages/*.html，输出到 dist/。

产物是自包含的单文件 HTML：零依赖、可离线双击打开（file:// 也能用）。

用法：
    python3 build.py            # 构建（先跑数据校验）
    python3 build.py --check    # 只校验：数据、标记完整性、dist 新鲜度
    python3 build.py --force    # 覆盖检测到被手改过的 dist 产物
    python3 build.py --no-validate   # 跳过数据校验（调试用）
"""
import argparse
import hashlib
import json
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "scripts"))
import merge_venues  # noqa: E402
import validate_data  # noqa: E402

ROOT = os.path.dirname(os.path.abspath(__file__))
DIST = os.path.join(ROOT, "dist")
MANIFEST = os.path.join(DIST, ".build-manifest.json")

# 源模板 -> 产物文件名。index.html 是落地页（总入口），发布到 GitHub Pages 的首页。
PAGES = {
    "src/pages/index.html": "index.html",
    "src/pages/bars.html": "shanghai_bars_livehouse_2026.html",
    "src/pages/bichi.html": "shanghai_bichi_saojie_2026.html",
    "src/pages/michelin.html": "shanghai_michelin_2026.html",
    "src/pages/eat.html": "shanghai_eat_2026.html",
}

# 产物 -> (店铺数据来源 JSON 列表, 预期条数)。用于 --check 的产物自检。
# 多个来源时按 merge_venues 的规则合并（如 eat 页把 bichi + michelin 合成一份）。
# 落地页不含任何内联数据，故来源为空、预期条数为 0。
EXPECT = {
    "index.html": ([], 0),
    "shanghai_bars_livehouse_2026.html": (["data/venues/bars.json"], 37),
    "shanghai_bichi_saojie_2026.html": (["data/venues/bichi.json"], 58),
    "shanghai_michelin_2026.html": (["data/venues/michelin.json"], 86),
    "shanghai_eat_2026.html": (["data/venues/bichi.json", "data/venues/michelin.json"], 131),
}


def expected_records(specs):
    """按 EXPECT 的来源列表取出（必要时合并）记录，用于产物自检。"""
    if not specs:
        return []
    if len(specs) == 1:
        return read_json(specs[0])
    return merge_venues.merge_sources(
        [(os.path.splitext(os.path.basename(p))[0], read_json(p)) for p in specs])

HEADER = ("<!-- GENERATED by build.py from {src} — DO NOT EDIT.\n"
          "     改数据请改 data/ 下的 JSON，然后跑 ./render.sh 重新生成。 -->\n")

# 匹配一整块注入标记：
#   <ind>/* @@BUILD:json <源路径> -> <目标名>@@ */
#   ...占位内容...
#   <ind>/* @@BUILD:end@@ */
BUILD_RE = re.compile(
    r'^(?P<ind>[ \t]*)/\* @@BUILD:(?P<kind>[a-z]+)[ \t]+(?P<src>[^\s]+?)'
    r'(?:[ \t]*->[ \t]*(?P<target>[A-Za-z_$][\w$]*))?[ \t]*@@ \*/'
    r'(?P<inner>.*?)'
    r'^(?P=ind)/\* @@BUILD:end@@ \*/',
    re.S | re.M,
)

# 落地页里的站内链接（只取同目录的 .html 产物，忽略外链与锚点）
LINK_RE = re.compile(r'href="([^"#?:/]+\.html)"')


def read_text(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def read_json(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as f:
        return json.load(f)


def safe_json(value):
    """紧凑 JSON；把 `</` 转义成 `<\\/`，避免数据里出现 `</script>` 提前闭合脚本。"""
    text = json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    return text.replace("</", "<\\/")


def serialize(value, indent):
    """数组按「一条一行」输出：可读性尚可，体积接近紧凑 JSON。

    例如 indent='' 时：
        [
        {"a":1},
        {"a":2}
        ]
    """
    if not isinstance(value, list):
        return safe_json(value)
    if not value:
        return "[]"
    parts = [safe_json(v) for v in value]
    return "[\n" + indent + (",\n" + indent).join(parts) + "\n" + indent + "]"


def indent_block(text, indent):
    """给多行文本的每一行加前缀缩进（用于内联 JS 文件）。"""
    lines = text.split("\n")
    # 去掉结尾空行，避免多出一堆空白
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(indent + ln if ln else ln for ln in lines)


def render_page(src_rel, for_check=False):
    """渲染一个源模板，返回产物文本。标记缺失/残留都会报错。"""
    src_path = os.path.join(ROOT, src_rel)
    src = read_text(src_path)
    total_markers = src.count("@@BUILD:")

    used = [0]

    def repl(m):
        used[0] += 1
        ind = m.group("ind")
        kind = m.group("kind")
        rel = m.group("src")
        target = m.group("target")

        def require(rel_path):
            if not os.path.exists(os.path.join(ROOT, rel_path)):
                raise SystemExit("{}: 标记引用的文件不存在: {}".format(src_rel, rel_path))

        if kind == "json":
            if not target:
                raise SystemExit("{}: json 标记缺少 `-> 目标名`".format(src_rel))
            require(rel)
            value = read_json(rel)
            return "{ind}const {name} = {body};".format(
                ind=ind, name=target, body=serialize(value, ind))
        if kind == "js":
            require(rel)
            body = read_text(os.path.join(ROOT, rel))
            # 内联进 <script> 的代码里出现 </script 会被解析器当成结束标签：整段脚本
            # 被截断，后面全部变成 HTML 文本。资源里不该有，出现就是有意的注入，拦掉。
            if re.search(r"</script", body, re.I):
                raise SystemExit("{}: {} 里含 </script，不能内联进脚本".format(src_rel, rel))
            return "{}{}".format(ind, indent_block(body, ind))
        if kind == "css":
            # 构建期内联静态 CSS（tailwind.css / mobile.css / vendor/leaflet/leaflet.css）。
            # 之前是 <script src="https://cdn.tailwindcss.com">：浏览器里跑 JIT，
            # 手机首屏先裸排版再跳样式，离线打开则完全没有样式。
            require(rel)
            body = read_text(os.path.join(ROOT, rel))
            if re.search(r"</style", body, re.I):
                raise SystemExit("{}: {} 里含 </style，不能内联进样式".format(src_rel, rel))
            return "{}{}".format(ind, indent_block(body, ind))
        if kind == "merge":
            # 多个数据源逗号分隔，按 merge_venues 规则合成一份（见 src/pages/eat.html）
            if not target:
                raise SystemExit("{}: merge 标记缺少 `-> 目标名`".format(src_rel))
            specs = rel.split(",")
            for s in specs:
                require(s)
            value = merge_venues.merge_sources([
                (os.path.splitext(os.path.basename(s))[0], read_json(s)) for s in specs])
            return "{ind}const {name} = {body};".format(
                ind=ind, name=target, body=serialize(value, ind))
        if kind == "count":
            # 把数据源的记录条数直接写进产物（见 src/pages/index.html 的「N 家」）。
            # 数字由数据算出，避免页面里的手写条数随数据改动而说谎。
            if target:
                raise SystemExit("{}: count 标记不接受 `-> 目标名`".format(src_rel))
            specs = rel.split(",")
            for s in specs:
                require(s)
            return "{}{}".format(ind, len(expected_records(specs)))
        raise SystemExit("{}: 未知的标记类型 {!r}".format(src_rel, kind))

    out = BUILD_RE.sub(repl, src)

    if used[0] * 2 != total_markers:
        raise SystemExit(
            "{}: 标记未全部识别（识别 {} 块 / 共出现 {} 个 @@BUILD:，"
            "标记必须整行成对出现且缩进一致）".format(src_rel, used[0], total_markers))
    if "@@BUILD:" in out:
        raise SystemExit("{}: 产物里仍有残留标记，模板格式有问题".format(src_rel))

    # 插入「生成物」文件头
    header = HEADER.format(src=src_rel)
    if out.startswith("<!DOCTYPE html>"):
        nl = out.index("\n") + 1
        out = out[:nl] + header + out[nl:]
    else:
        out = header + out
    return out


def sha256(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def load_manifest():
    if not os.path.exists(MANIFEST):
        return {}
    try:
        with open(MANIFEST, encoding="utf-8") as f:
            return json.load(f).get("pages", {})
    except (json.JSONDecodeError, OSError):
        return {}


def write_manifest(pages):
    os.makedirs(DIST, exist_ok=True)
    with open(MANIFEST, "w", encoding="utf-8") as f:
        json.dump({
            "generated_by": "build.py",
            "note": "记录每个产物的 sha256，用于检测 dist/ 是否被手改。",
            "pages": pages,
        }, f, ensure_ascii=False, indent=2)
        f.write("\n")


def check_artifacts(problems):
    """产物自检：无残留标记、条数正确、每条 key 都在、与源模板一致。"""
    for src_rel, dist_name in PAGES.items():
        dist_path = os.path.join(DIST, dist_name)
        if not os.path.exists(dist_path):
            continue
        content = read_text(dist_path)
        if "@@BUILD:" in content:
            problems.append("{}: 产物里有残留的 @@BUILD 标记".format(dist_name))

        data_specs, expect_n = EXPECT[dist_name]
        records = expected_records(data_specs)
        if len(records) != expect_n:
            problems.append("{}: 数据 {} 合并后 {} 条，预期 {}".format(
                dist_name, "+".join(data_specs), len(records), expect_n))
        missing = [r["key"] for r in records if r.get("key") and r["key"] not in content]
        if missing:
            problems.append("{}: 有 {} 条记录未出现在产物中（如 {}）".format(
                dist_name, len(missing), missing[:3]))

        fresh = render_page(src_rel)
        if sha256(fresh) != sha256(content):
            problems.append("{}: 产物与源模板不一致，需要重新构建".format(dist_name))

        check_no_external_assets(content, dist_name, problems)
        check_inlined_runtime(content, dist_name, problems)
        check_class_coverage(content, dist_name, problems)
        check_mobile_shell_markers(content, dist_name, problems)
    print("  产物自检完成（{} 个页面）".format(len(PAGES)))


SCRIPT_SRC_RE = re.compile(r'<script[^>]*\ssrc="([^"]+)"')
LINK_SHEET_RE = re.compile(r'<link[^>]*rel="stylesheet"[^>]*>')


def check_no_external_assets(content, dist_name, problems):
    """零依赖不变量：产物不许再挂任何外链的 JS / CSS。

    这条断言是防「又悄悄加回 CDN」的：改一版主题就顺手加个 <link>，然后手机端在
    弱网 / 离线时又退回裸排版。Google Fonts 也在排查范围内 —— 大陆访问
    fonts.googleapis.com 本来就慢（多数时候直接超时），已改成系统字体栈。"""
    external = [u for u in SCRIPT_SRC_RE.findall(content)
                if u.startswith(("http://", "https://", "//"))]
    for tag in LINK_SHEET_RE.findall(content):
        m = re.search(r'href="([^"]+)"', tag)
        if m and m.group(1).startswith(("http://", "https://", "//")):
            external.append(m.group(1))
    if external:
        problems.append("{}: 产物里还有外链资源 {}（应为内联零依赖）".format(
            dist_name, sorted(set(external))[:3]))
    # 只在「真的会发请求」的位置查 Google Fonts：注释里提到它不算
    fonts = re.findall(r'(?:href|src)="[^"]*fonts\.(?:googleapis|gstatic)\.com', content)
    fonts += re.findall(r'url\(\s*[\'"]?https?://fonts\.', content)
    if fonts:
        problems.append("{}: 产物里还有 Google Fonts 请求（{} 处），请改用系统字体栈".format(
            dist_name, len(fonts)))


# Leaflet 的 @preserve 版权头（leaflet.js 第一行），版本升级也不会变。
LEAFLET_BANNER = "a JS library for interactive maps"


def check_inlined_runtime(content, dist_name, problems):
    """反面断言：该内联的运行时是不是真的进来了。

    这条是踩坑之后加的。把 `cdn.tailwindcss.com` / `unpkg` 的 <script src> 删掉、
    却忘了把对应文件按 @@BUILD:js 标记内联进来时，check_no_external_assets 反而
    「更绿」—— 产物确实不再依赖外网，但也彻底没有那个库了。这种错误构建期一片
    安静，浏览器只在运行时丢一句 `L is not defined`，地图整块空白。
    所以这里正面断言：页面里用了 Leaflet，产物里就必须能看见 Leaflet 的运行时。"""
    if 'id="leaflet-map"' not in content:
        return
    if LEAFLET_BANNER not in content:
        problems.append(
            "{}: 页面用了 Leaflet，但产物里找不到 Leaflet 运行时"
            "（是不是漏了 `@@BUILD:js src/static/vendor/leaflet/leaflet.js@@` 标记？）".format(
                dist_name))


def css_escape(token):
    """把类名转成 CSS 选择器里的写法（Tailwind 转义规则）：z-[1000] -> z-\\[1000\\]。"""
    return "".join(c if (c.isalnum() or c in "-_") else "\\" + c for c in token)


STYLE_RE = re.compile(r"<style[^>]*>(.*?)</style>", re.S)
CLASS_ATTR_RE = re.compile(r'class="([^"]*)"')
# class 属性里一旦出现这些东西，说明它不是一份「静态类名清单」，而是 JS 代码
# （模板插值 / 字符串拼接，例如 class="tag ${s === 'A' ? 'src-a' : ''}"）
CLASS_ATTR_CODE_CHARS = set("'\"`${}=?,;+()<>|&\n\t*")
CLASS_TOKEN_OK_RE = re.compile(r"^[A-Za-z0-9_!#%&*+:./\-\[\]()]+$")


def check_class_coverage(content, dist_name, problems):
    """逐个类名核对产物里内联的 CSS 是否真的定义了它。

    为什么需要这条：Tailwind 的 CSS 是构建期生成的一份静态文件，而类名写在页面里。
    改了页面却忘了跑 scripts/build_css.sh，类名就不会出现在 CSS 里，表现是「某个
    元素悄悄没了样式」—— 正是手机端最要命的失败模式，且浏览器不会报任何错。这里把
    它变成构建期错误。

    判定范围限定在 <style> 里的选择器文本，所以页面自定义的类名（.chip、.rest-item、
    .m-icon 等）会被认成「已定义」，只有真正没生成的 Tailwind 类名才报错。

    有意不覆盖：JS 里拼出来的类名（class="…${x}…"、className = 'a ' + b）。它们
    要么带插值要么带拼接，没法可靠地区分「类名」与「变量名」，硬判会全是误报；
    而这些类名通常同时以静态形式出现在页面里，漏判的代价可以接受。"""
    css_text = "\n".join(STYLE_RE.findall(content))
    if not css_text:
        return
    unknown = []
    for attrs in CLASS_ATTR_RE.findall(content):
        if any(c in CLASS_ATTR_CODE_CHARS for c in attrs):
            continue
        for token in attrs.split():
            if not CLASS_TOKEN_OK_RE.match(token) or not any(c.isalnum() for c in token):
                continue
            if ("." + token) in css_text or ("." + css_escape(token)) in css_text:
                continue
            unknown.append(token)
    if unknown:
        problems.append(
            "{}: 这些类名在产物 CSS 里找不到定义 {}（新增 Tailwind 类名后要跑 "
            "./scripts/build_css.sh 重新生成 src/static/tailwind.css）".format(
                dist_name, sorted(set(unknown))[:6]))


def check_mobile_shell_markers(content, dist_name, problems):
    """手机端外壳的结构不变量。

    两条都是「改一行就静默坏掉、桌面上还看不出来」的坑，所以做成构建期断言：

    1) `data-m-sheet` 不能挂在 `#detail-card` 自己身上。mobile.css 里
       `html.m-mobile #detail-card { position: relative !important }` 是给「抽屉里的
       详情卡」用的（抽屉自己是 position:fixed）。一旦两个属性落在同一个元素上，
       !important 会把抽屉的 fixed 顶掉，闭合态的详情卡就停在视口正中 —— bars 页
       真踩过这个坑，当时桌面端一切正常，只有手机上多出一块浮窗。

    2) 百度链接不许带 `target="_blank"`。scheme 调起必须同一个 tab 里走
       `location.href`；`_blank` 在新标签里跑，移动浏览器常按弹窗拦掉，失败后还留下
       一个空白标签页回不去。
    """
    for m in re.finditer(r"<[a-zA-Z][^>]*>", content):
        tag = m.group(0)
        if 'id="detail-card"' in tag and "data-m-sheet" in tag:
            problems.append(
                "{}: #detail-card 上同时挂了 data-m-sheet —— mobile.css 给它的 "
                "position:relative !important 会把抽屉的 fixed 顶掉，手机上会多出一块"
                "浮在视口中间的详情卡。请把 data-m-sheet 挪到外层的容器上".format(dist_name))
            break

    for link_id in ("detail-nav", "detail-poi"):
        m = re.search(r"<a[^>]*id=\"{}\"[^>]*>".format(link_id), content)
        if not m:
            continue
        if "_blank" in m.group(0):
            problems.append(
                "{}: #{} 还带着 target=\"_blank\" —— App 调起要靠同一个 tab 的 "
                "location.href，新标签会被当弹窗拦掉".format(dist_name, link_id))

    # 手机端外壳要求「顶栏存在 + 至少一个抽屉」，否则 m-mobile 下页面会变成空白
    if 'id="m-bar"' in content and "data-m-sheet" not in content:
        problems.append("{}: 有顶栏 #m-bar 却没有任何 data-m-sheet 抽屉".format(dist_name))


def check_landing(problems):
    """落地页自检：站内链接都有对应产物，且没有漏挂任何地图页。"""
    dist_path = os.path.join(DIST, "index.html")
    if not os.path.exists(dist_path):
        problems.append("index.html: 落地页产物不存在")
        return
    linked = set(LINK_RE.findall(read_text(dist_path)))

    broken = sorted(h for h in linked if not os.path.exists(os.path.join(DIST, h)))
    if broken:
        problems.append("index.html: 链接指向不存在的产物 {}".format(broken))

    maps = {name for name in PAGES.values() if name != "index.html"}
    orphans = sorted(maps - linked)
    if orphans:
        problems.append("index.html: 这些地图页没被落地页链接 {}".format(orphans))
    print("  落地页自检完成（链接 {} 个产物）".format(len(maps)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="只校验，不写盘")
    ap.add_argument("--force", action="store_true", help="覆盖被手改过的产物")
    ap.add_argument("--no-validate", action="store_true", help="跳过数据校验")
    args = ap.parse_args()

    # ---------- 1) 数据校验 ----------
    if not args.no_validate:
        errors = validate_data.validate_all()
        if errors:
            print("\n数据校验未通过（{} 个问题）：".format(len(errors)))
            for e in errors:
                print("  - " + e)
            sys.exit(1)
        print("  数据校验通过")

    # ---------- 2) 渲染 ----------
    rendered = {}
    for src_rel, dist_name in PAGES.items():
        rendered[dist_name] = render_page(src_rel)
    print("  渲染完成：{} 个页面".format(len(rendered)))

    # ---------- 3) 产物自检 ----------
    if args.check:
        print("\n[--check] 校验产物：")
        problems = []
        if not os.path.isdir(DIST):
            problems.append("dist/ 不存在，需要先跑 python3 build.py")
        else:
            check_artifacts(problems)
            check_landing(problems)
        if problems:
            print("\n发现 {} 个问题：".format(len(problems)))
            for p in problems:
                print("  - " + p)
            sys.exit(1)
        print("\n校验通过。")
        return

    # ---------- 4) 写盘（含防手改检查） ----------
    prev = load_manifest()
    os.makedirs(DIST, exist_ok=True)
    new_manifest = {}
    tampered = []

    for dist_name, content in rendered.items():
        dist_path = os.path.join(DIST, dist_name)
        if os.path.exists(dist_path) and not args.force:
            on_disk = read_text(dist_path)
            recorded = prev.get(dist_name, {}).get("sha256")
            if recorded is None:
                if sha256(on_disk) != sha256(content):
                    tampered.append((dist_name, "没有构建记录，但与当前源不一致"))
            elif sha256(on_disk) != recorded:
                tampered.append((dist_name, "内容与上次构建记录不符（疑似手改）"))
        new_manifest[dist_name] = {
            "source": [k for k, v in PAGES.items() if v == dist_name][0],
            "sha256": sha256(content),
            "bytes": len(content.encode("utf-8")),
        }
        if not args.check:
            with open(dist_path, "w", encoding="utf-8") as f:
                f.write(content)

    if tampered:
        print("\n以下产物被改动过，已中止以免覆盖你的修改：")
        for name, why in tampered:
            print("  - {}: {}".format(name, why))
        print("\n确认要覆盖请加 --force。")
        sys.exit(1)

    write_manifest(new_manifest)

    print("\n构建完成 → dist/")
    for name, meta in new_manifest.items():
        print("  {:<42} {:>9,} B".format(name, meta["bytes"]))
    src_sizes = sum(os.path.getsize(os.path.join(ROOT, s)) for s in PAGES)
    dist_sizes = sum(m["bytes"] for m in new_manifest.values())
    print("  源模板合计 {:,} B → 产物合计 {:,} B".format(src_sizes, dist_sizes))


if __name__ == "__main__":
    main()
