#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""把 data/*.json 与 src/static/*.js 内联进 src/pages/*.html，输出到 dist/。

产物是自包含的单文件 HTML：零依赖、可离线双击打开（file:// 也能用）。

用法：
    python3 build.py            # 构建（先跑数据校验）
    python3 build.py --check    # 只校验：数据、标记完整性、dist 新鲜度
    python3 build.py --force    # 覆盖检测到被手改过的 dist 产物
    python3 build.py --no-validate   # 跳过数据校验（调试用）
"""
import argparse
import hashlib
import json
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "scripts"))
import validate_data  # noqa: E402

ROOT = os.path.dirname(os.path.abspath(__file__))
DIST = os.path.join(ROOT, "dist")
MANIFEST = os.path.join(DIST, ".build-manifest.json")

# 源模板 -> 产物文件名
PAGES = {
    "src/pages/bars.html": "shanghai_bars_livehouse_2026.html",
    "src/pages/bichi.html": "shanghai_bichi_saojie_2026.html",
    "src/pages/michelin.html": "shanghai_michelin_2026.html",
}

# 产物 -> (店铺数据 JSON, 预期条数, 唯一键字段)。用于 --check 的产物自检。
EXPECT = {
    "shanghai_bars_livehouse_2026.html": ("data/venues/bars.json", 37),
    "shanghai_bichi_saojie_2026.html": ("data/venues/bichi.json", 59),
    "shanghai_michelin_2026.html": ("data/venues/michelin.json", 86),
}

HEADER = ("<!-- GENERATED by build.py from {src} — DO NOT EDIT.\n"
          "     改数据请改 data/ 下的 JSON，然后跑 ./render.sh 重新生成。 -->\n")

# 匹配一整块注入标记：
#   <ind>/* @@BUILD:json <源路径> -> <目标名>@@ */
#   ...占位内容...
#   <ind>/* @@BUILD:end@@ */
BUILD_RE = re.compile(
    r'^(?P<ind>[ \t]*)/\* @@BUILD:(?P<kind>[a-z]+)[ \t]+(?P<src>[^\s]+?)'
    r'(?:[ \t]*->[ \t]*(?P<target>[A-Za-z_$][\w$]*))?[ \t]*@@ \*/'
    r'(?P<inner>.*?)'
    r'^(?P=ind)/\* @@BUILD:end@@ \*/',
    re.S | re.M,
)


def read_text(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def read_json(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as f:
        return json.load(f)


def safe_json(value):
    """紧凑 JSON；把 `</` 转义成 `<\\/`，避免数据里出现 `</script>` 提前闭合脚本。"""
    text = json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    return text.replace("</", "<\\/")


def serialize(value, indent):
    """数组按「一条一行」输出：可读性尚可，体积接近紧凑 JSON。

    例如 indent='' 时：
        [
        {"a":1},
        {"a":2}
        ]
    """
    if not isinstance(value, list):
        return safe_json(value)
    if not value:
        return "[]"
    parts = [safe_json(v) for v in value]
    return "[\n" + indent + (",\n" + indent).join(parts) + "\n" + indent + "]"


def indent_block(text, indent):
    """给多行文本的每一行加前缀缩进（用于内联 JS 文件）。"""
    lines = text.split("\n")
    # 去掉结尾空行，避免多出一堆空白
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(indent + ln if ln else ln for ln in lines)


def render_page(src_rel, for_check=False):
    """渲染一个源模板，返回产物文本。标记缺失/残留都会报错。"""
    src_path = os.path.join(ROOT, src_rel)
    src = read_text(src_path)
    total_markers = src.count("@@BUILD:")

    used = [0]

    def repl(m):
        used[0] += 1
        ind = m.group("ind")
        kind = m.group("kind")
        rel = m.group("src")
        target = m.group("target")
        data_path = os.path.join(ROOT, rel)
        if not os.path.exists(data_path):
            raise SystemExit("{}: 标记引用的文件不存在: {}".format(src_rel, rel))

        if kind == "json":
            if not target:
                raise SystemExit("{}: json 标记缺少 `-> 目标名`".format(src_rel))
            value = read_json(rel)
            return "{ind}const {name} = {body};".format(
                ind=ind, name=target, body=serialize(value, ind))
        if kind == "js":
            body = indent_block(read_text(data_path), ind)
            return "{}{}".format(ind, body)
        raise SystemExit("{}: 未知的标记类型 {!r}".format(src_rel, kind))

    out = BUILD_RE.sub(repl, src)

    if used[0] * 2 != total_markers:
        raise SystemExit(
            "{}: 标记未全部识别（识别 {} 块 / 共出现 {} 个 @@BUILD:，"
            "标记必须整行成对出现且缩进一致）".format(src_rel, used[0], total_markers))
    if "@@BUILD:" in out:
        raise SystemExit("{}: 产物里仍有残留标记，模板格式有问题".format(src_rel))

    # 插入「生成物」文件头
    header = HEADER.format(src=src_rel)
    if out.startswith("<!DOCTYPE html>"):
        nl = out.index("\n") + 1
        out = out[:nl] + header + out[nl:]
    else:
        out = header + out
    return out


def sha256(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def load_manifest():
    if not os.path.exists(MANIFEST):
        return {}
    try:
        with open(MANIFEST, encoding="utf-8") as f:
            return json.load(f).get("pages", {})
    except (json.JSONDecodeError, OSError):
        return {}


def write_manifest(pages):
    os.makedirs(DIST, exist_ok=True)
    with open(MANIFEST, "w", encoding="utf-8") as f:
        json.dump({
            "generated_by": "build.py",
            "note": "记录每个产物的 sha256，用于检测 dist/ 是否被手改。",
            "pages": pages,
        }, f, ensure_ascii=False, indent=2)
        f.write("\n")


def check_artifacts(problems):
    """产物自检：无残留标记、条数正确、每条 key 都在、与源模板一致。"""
    for src_rel, dist_name in PAGES.items():
        dist_path = os.path.join(DIST, dist_name)
        if not os.path.exists(dist_path):
            continue
        content = read_text(dist_path)
        if "@@BUILD:" in content:
            problems.append("{}: 产物里有残留的 @@BUILD 标记".format(dist_name))

        data_rel, expect_n = EXPECT[dist_name]
        records = read_json(data_rel)
        if len(records) != expect_n:
            problems.append("{}: {} 有 {} 条，预期 {}".format(
                dist_name, data_rel, len(records), expect_n))
        missing = [r["key"] for r in records if r.get("key") and r["key"] not in content]
        if missing:
            problems.append("{}: 有 {} 条记录未出现在产物中（如 {}）".format(
                dist_name, len(missing), missing[:3]))

        fresh = render_page(src_rel)
        if sha256(fresh) != sha256(content):
            problems.append("{}: 产物与源模板不一致，需要重新构建".format(dist_name))
    print("  产物自检完成（{} 个页面）".format(len(PAGES)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="只校验，不写盘")
    ap.add_argument("--force", action="store_true", help="覆盖被手改过的产物")
    ap.add_argument("--no-validate", action="store_true", help="跳过数据校验")
    args = ap.parse_args()

    # ---------- 1) 数据校验 ----------
    if not args.no_validate:
        errors = validate_data.validate_all()
        if errors:
            print("\n数据校验未通过（{} 个问题）：".format(len(errors)))
            for e in errors:
                print("  - " + e)
            sys.exit(1)
        print("  数据校验通过")

    # ---------- 2) 渲染 ----------
    rendered = {}
    for src_rel, dist_name in PAGES.items():
        rendered[dist_name] = render_page(src_rel)
    print("  渲染完成：{} 个页面".format(len(rendered)))

    # ---------- 3) 产物自检 ----------
    if args.check:
        print("\n[--check] 校验产物：")
        problems = []
        if not os.path.isdir(DIST):
            problems.append("dist/ 不存在，需要先跑 python3 build.py")
        else:
            check_artifacts(problems)
        if problems:
            print("\n发现 {} 个问题：".format(len(problems)))
            for p in problems:
                print("  - " + p)
            sys.exit(1)
        print("\n校验通过。")
        return

    # ---------- 4) 写盘（含防手改检查） ----------
    prev = load_manifest()
    os.makedirs(DIST, exist_ok=True)
    new_manifest = {}
    tampered = []

    for dist_name, content in rendered.items():
        dist_path = os.path.join(DIST, dist_name)
        if os.path.exists(dist_path) and not args.force:
            on_disk = read_text(dist_path)
            recorded = prev.get(dist_name, {}).get("sha256")
            if recorded is None:
                if sha256(on_disk) != sha256(content):
                    tampered.append((dist_name, "没有构建记录，但与当前源不一致"))
            elif sha256(on_disk) != recorded:
                tampered.append((dist_name, "内容与上次构建记录不符（疑似手改）"))
        new_manifest[dist_name] = {
            "source": [k for k, v in PAGES.items() if v == dist_name][0],
            "sha256": sha256(content),
            "bytes": len(content.encode("utf-8")),
        }
        if not args.check:
            with open(dist_path, "w", encoding="utf-8") as f:
                f.write(content)

    if tampered:
        print("\n以下产物被改动过，已中止以免覆盖你的修改：")
        for name, why in tampered:
            print("  - {}: {}".format(name, why))
        print("\n确认要覆盖请加 --force。")
        sys.exit(1)

    write_manifest(new_manifest)

    print("\n构建完成 → dist/")
    for name, meta in new_manifest.items():
        print("  {:<42} {:>9,} B".format(name, meta["bytes"]))
    src_sizes = sum(os.path.getsize(os.path.join(ROOT, s)) for s in PAGES)
    dist_sizes = sum(m["bytes"] for m in new_manifest.values())
    print("  源模板合计 {:,} B → 产物合计 {:,} B".format(src_sizes, dist_sizes))


if __name__ == "__main__":
    main()
